import Head from "next/head";
import Image from "next/image";
import { HeartIcon, PlaneIcon, XIcon } from "@/components/Icons";
import { PopupMenu, PopupMenuContext } from "@/components/PopupMenu";
import ActionButton from "@/components/ActionButton";
import ImageSlider from "@/components/ImageSlider";
import ColorPicker from "@/components/ColorPicker";
import SizePicker from "@/components/SizePicker";
import HeartButton from "@/components/HeartButton";
import { EPopupLayouts } from "@/components/PopupLayouts";
import usePopupManager from "@/hooks/usePopupManager";
import { useContext } from "react";
import useUserInfo, { UserInfoContext } from "@/hooks/useUserInfo";
import React from "react";
import { GetServerSideProps } from "next";

const LayoutOrder = [
  EPopupLayouts.UserDataPage,
  EPopupLayouts.SignUpPromptPage,
  EPopupLayouts.ShippingOptionPage,
  EPopupLayouts.DisplayTotalPage,
];
type Image = {
  bgColor: string;
  src: string;
};
type Product = {
  desc: string;
  id: string;
  name: string;
  category: string;
  sizes: string[];
  colors: string[];
  images: Image[];
  sale: number;
  price: number;
};

export default function Home({ product }: { product: Product }) {
  const popupManager = usePopupManager(LayoutOrder);
  const onSubmit = () => {
    popupManager.setIsVisible(true);
  };
  const UserInfo = useUserInfo();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header>
        <nav className="max-w-7xl p-4 flex justify-center max-h-20 h-auto w-auto ">
          <Image alt="logo" src={"/next.svg"} width={100} height={50} />
        </nav>
      </header>
      <UserInfoContext.Provider value={{ ...UserInfo }}>
        <PopupMenuContext.Provider value={popupManager}>
          <main
            className={`max-w-7xl grid grid-cols-1 lg:grid-cols-2 h-full lg:h-full`}
          >
            <ImageSlider images={product.images} />
            <div className="px-4 child:pt-4 pb-8 flex flex-col">
              {/* Title section */}
              <div className="flex flex-col">
                <div className="flex justify-between items-center w-full">
                  <h1
                    className="font-thin
               text-xl font-rounded"
                  >
                    {product.name}
                  </h1>
                  <h2 className="text-lg font-rounded font-thin">
                    ${product.price / 100}
                  </h2>
                </div>
                <div className="flex justify-between w-full text-gray-400">
                  <p>{product.category}</p>
                  {product.sale && <p>{product.sale}% off</p>}
                </div>
              </div>
              <div className="sm:line-clamp-3 md:line-clamp-4 lg:hidden ">
                {product.desc}
              </div>
              {product.sizes.length ? (
                <SizePicker className="mt-auto" sizes={product.sizes} />
              ) : null}
              {product.colors.length ? (
                <ColorPicker colors={product.colors} />
              ) : null}
              <div className="flex items-center justify-center child:mx-4 pt-12 lg:mt-20">
                <ActionButton
                  className="w-3/5 h-12 rounded-full"
                  onClick={onSubmit}
                >
                  Buy Now
                </ActionButton>

                <HeartButton />
              </div>
            </div>
            <div className="hidden lg:block col-span-2 mt-6 p-4">
              {product.desc}
            </div>
            <PopupMenu />
          </main>
        </PopupMenuContext.Provider>
      </UserInfoContext.Provider>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  product: Product;
}> = async (context) => {
  console.log();
  const store =
    // get store domain

    // query redis to get the store

    console.log(context.req.headers.host);

  const product: Product = {
    name: "Nike Air Edge 270",
    category: "Men's shoes",
    images: [
      {
        src: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1b8e8e0e-acdd-429a-986c-24ccb2254d05/air-max-270-womens-shoes-Pgb94t.png",
        bgColor: "#f5f5f5",
      },
      {
        src: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/3b761920-a1bc-442c-b04d-6eafabc87e10/air-max-270-womens-shoes-Pgb94t.png",
        bgColor: "#f5f5f5",
      },
      {
        src: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/57c7f846-26e0-4a63-a643-fa6cbe66cac5/air-max-270-womens-shoes-Pgb94t.png",
        bgColor: "#f5f5f5",
      },
      {
        src: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/d4b051cb-f9bc-4d85-a4f9-299f85ffcc90/air-max-270-womens-shoes-Pgb94t.png",
        bgColor: "#f5f5f5",
      },
      {
        src: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1f799a57-b31b-4db2-b715-46275aa29023/air-max-270-womens-shoes-Pgb94t.png",
        bgColor:
          "https://cdn.shopify.com/s/files/1/0625/9965/9766/files/mike-meyers--haAxbjiHds-unsplash_592x.jpg?v=1663072149",
      },
    ],
    desc: "The Nike Air Max 270 is a stylish and comfortable sneaker that features a large Air Max unit in the heel for superior cushioning and support. With a breathable mesh upper and a variety of bold colorways, the 270 is a popular choice for both athletic performance and casual wear. Its sleek design and innovative technology make it a must-have for sneaker enthusiasts and Nike fans alike.",
    price: 15000,
    colors: ["#333", "#222", "F1F3F4"],
    id: "243532",
    sale: 150,
    sizes: [
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
    ],
  };
  return {
    props: {
      product: product,
    },
  };
};
